[tool.poetry]
name = "telegram-newsletter"
version = "0.1.0"
description = ""
authors = ["ycalk <alosev752@gmail.com>"]
packages = [
    {include = "newsletter/admin_panel",from = "bases"},
    {include = "newsletter/email_sender",from = "components"},
    {include = "newsletter/database",from = "components"},
    {include = "newsletter/logging",from = "components"},
    {include = "newsletter/bot",from = "bases"},
    {include = "newsletter/api_client",from = "components"},
    {include = "newsletter/migrator",from = "bases"},
    {include = "newsletter/channel_id_encryption",from = "components"},
    {include = "newsletter/dto",from = "components"},
    {include = "newsletter/media_proxy",from = "bases"},
    {include = "newsletter/view_tracker",from = "bases"},
    {include = "newsletter/unsubscribe_handler",from = "bases"},
    {include = "newsletter/scheduler",from = "bases"},
]

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
pydantic-settings = "^2.13.1"
fastapi = {extras = ["standard"], version = "^0.135.1"}
dishka = {extras = ["fastapi", "aiogram"], version = "^1.9.1"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.45"}
asyncpg = "^0.31.0"
structlog = "^25.5.0"
opentelemetry-api = "^1.40.0"
opentelemetry-sdk = "^1.40.0"
opentelemetry-exporter-otlp = "^1.40.0"
opentelemetry-instrumentation-fastapi = "^0.61b0"
opentelemetry-instrumentation-sqlalchemy = "^0.61b0"
alembic = "^1.18.4"
httpx = "^0.28.1"
resend = "^2.26.0"
hashids = "^1.3.1"
aiogram = "^3.26.0"
email-validator = "^2.3.0"
redis = "^7.4.0"
hishel = {extras = ["httpx"], version = "^1.1.9"}
sendgrid = "^6.12.5"
pillow = "^12.1.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
alembic = "newsletter.migrator:run"
test_response = "development.test_response:run"
encrypt_channel_id = "development.encrypt_channel_id:run"
bot = "newsletter.bot:run"
admin_panel = "newsletter.admin_panel:run"
media_proxy = "newsletter.media_proxy:run"
view_tracker = "newsletter.view_tracker:run"
scheduler = "newsletter.scheduler:run"