"""add newsletter subscription

Revision ID: 0e9b77df1079
Revises: f40e6073e469
Create Date: 2026-03-25 01:14:17.809027

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e9b77df1079"
down_revision: str | Sequence[str] | None = "f40e6073e469"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "channel_id", name="uq_user_channel"),
    )
    op.create_index(
        op.f("ix_newsletter_subscription_channel_id"),
        "newsletter_subscription",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_newsletter_subscription_user_id"),
        "newsletter_subscription",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_newsletter_subscription_user_id"), table_name="newsletter_subscription"
    )
    op.drop_index(
        op.f("ix_newsletter_subscription_channel_id"),
        table_name="newsletter_subscription",
    )
    op.drop_table("newsletter_subscription")
    # ### end Alembic commands ###
