"""Add viewed at field

Revision ID: 360f810f1341
Revises: 0e9b77df1079
Create Date: 2026-04-10 20:44:04.460361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "360f810f1341"
down_revision: str | Sequence[str] | None = "0e9b77df1079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "letter", sa.Column("viewed_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "letter",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("newsletter", "channel_messages_count")
    op.add_column(
        "newsletter_element",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "newsletter_element",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "telegram_user",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "telegram_user",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_user", "updated_at")
    op.drop_column("telegram_user", "created_at")
    op.drop_column("newsletter_element", "updated_at")
    op.drop_column("newsletter_element", "created_at")
    op.add_column(
        "newsletter",
        sa.Column(
            "channel_messages_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("letter", "updated_at")
    op.drop_column("letter", "viewed_at")
    # ### end Alembic commands ###
