"""Add send_at field to subscription

Revision ID: 592dd4bc5125
Revises: af17e7a801cd
Create Date: 2026-04-16 16:19:39.428192

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "592dd4bc5125"
down_revision: str | Sequence[str] | None = "af17e7a801cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "newsletter_subscription", sa.Column("send_at", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("newsletter_subscription", "send_at")
    # ### end Alembic commands ###
