"""Change message_id to UUID

Revision ID: 5a7c6a768fbc
Revises: 360f810f1341
Create Date: 2026-04-11 00:21:45.012566

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a7c6a768fbc"
down_revision: str | Sequence[str] | None = "360f810f1341"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "newsletter_element",
        "message_id",
        existing_type=sa.BIGINT(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using="gen_random_uuid()",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "newsletter_element",
        "message_id",
        existing_type=sa.Uuid(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        postgresql_using="0",
    )
    # ### end Alembic commands ###
