"""Storage scheme redesign

Revision ID: af17e7a801cd
Revises: f174e2c2ca5e
Create Date: 2026-04-15 15:13:44.814980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af17e7a801cd"
down_revision: str | Sequence[str] | None = "f174e2c2ca5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["logo_id"], ["media.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_message_channel_id"),
        "channel_message",
        ["channel_id"],
        unique=False,
    )

    op.create_table(
        "message_media_link",
        sa.Column("media_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["message_id"], ["channel_message.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("media_id"),
    )
    op.create_index(
        op.f("ix_message_media_link_message_id"),
        "message_media_link",
        ["message_id"],
        unique=False,
    )

    op.create_table(
        "letter_element",
        sa.Column("letter_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["letter_id"], ["letter.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["message_id"], ["channel_message.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("letter_id", "message_id"),
    )

    op.drop_constraint(op.f("letter_user_id_fkey"), "letter", type_="foreignkey")
    op.drop_constraint(op.f("letter_newsletter_id_fkey"), "letter", type_="foreignkey")

    op.drop_index(
        op.f("ix_newsletter_element_newsletter_id"), table_name="newsletter_element"
    )
    op.drop_table("newsletter_element")

    op.drop_index(op.f("ix_newsletter_channel_id"), table_name="newsletter")
    op.drop_table("newsletter")

    op.add_column(
        "letter", sa.Column("newsletter_subscription_id", sa.Uuid(), nullable=False)
    )
    op.drop_index(op.f("ix_letter_newsletter_id"), table_name="letter")
    op.drop_index(op.f("ix_letter_user_id"), table_name="letter")
    op.drop_constraint(op.f("uq_letter_newsletter_user"), "letter", type_="unique")

    op.create_index(
        op.f("ix_letter_newsletter_subscription_id"),
        "letter",
        ["newsletter_subscription_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "letter",
        "newsletter_subscription",
        ["newsletter_subscription_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_column("letter", "user_id")
    op.drop_column("letter", "newsletter_id")
    op.add_column(
        "newsletter_subscription",
        sa.Column("unsubscribed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_foreign_key(
        None,
        "newsletter_subscription",
        "channel",
        ["channel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "newsletter_subscription", type_="foreignkey")
    op.drop_constraint(None, "letter", type_="foreignkey")

    op.create_table(
        "newsletter",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("channel_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "messages_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "messages_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("newsletter_pkey")),
    )
    op.create_index(
        op.f("ix_newsletter_channel_id"), "newsletter", ["channel_id"], unique=False
    )

    op.create_table(
        "newsletter_element",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("newsletter_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["newsletter_id"],
            ["newsletter.id"],
            name=op.f("newsletter_element_newsletter_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("newsletter_element_pkey")),
    )
    op.create_index(
        op.f("ix_newsletter_element_newsletter_id"),
        "newsletter_element",
        ["newsletter_id"],
        unique=False,
    )

    op.add_column(
        "letter",
        sa.Column("newsletter_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "letter", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )

    op.create_foreign_key(
        op.f("letter_newsletter_id_fkey"),
        "letter",
        "newsletter",
        ["newsletter_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("letter_user_id_fkey"),
        "letter",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_index(op.f("ix_letter_newsletter_subscription_id"), table_name="letter")
    op.create_unique_constraint(
        op.f("uq_letter_newsletter_user"),
        "letter",
        ["newsletter_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_letter_user_id"), "letter", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_letter_newsletter_id"), "letter", ["newsletter_id"], unique=False
    )

    op.drop_column("letter", "newsletter_subscription_id")
    op.drop_column("newsletter_subscription", "unsubscribed_at")

    op.drop_table("letter_element")
    op.drop_index(
        op.f("ix_message_media_link_message_id"), table_name="message_media_link"
    )
    op.drop_table("message_media_link")
    op.drop_index(op.f("ix_channel_message_channel_id"), table_name="channel_message")
    op.drop_table("channel_message")
    op.drop_table("channel")
    op.drop_table("media")
    # ### end Alembic commands ###
