"""create_models

Revision ID: f40e6073e469
Revises:
Create Date: 2026-03-24 20:16:31.377630

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f40e6073e469"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_messages_count", sa.Integer(), nullable=False),
        sa.Column("messages_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("messages_to", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_newsletter_channel_id"), "newsletter", ["channel_id"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "letter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("newsletter_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["newsletter_id"], ["newsletter.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "newsletter_id", "user_id", name="uq_letter_newsletter_user"
        ),
    )
    op.create_index(
        op.f("ix_letter_newsletter_id"), "letter", ["newsletter_id"], unique=False
    )
    op.create_index(op.f("ix_letter_user_id"), "letter", ["user_id"], unique=False)
    op.create_table(
        "newsletter_element",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("newsletter_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["newsletter_id"], ["newsletter.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_newsletter_element_newsletter_id"),
        "newsletter_element",
        ["newsletter_id"],
        unique=False,
    )
    op.create_table(
        "telegram_user",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_telegram_user_telegram_id"),
        "telegram_user",
        ["telegram_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_user_telegram_id"), table_name="telegram_user")
    op.drop_table("telegram_user")
    op.drop_index(
        op.f("ix_newsletter_element_newsletter_id"), table_name="newsletter_element"
    )
    op.drop_table("newsletter_element")
    op.drop_index(op.f("ix_letter_user_id"), table_name="letter")
    op.drop_index(op.f("ix_letter_newsletter_id"), table_name="letter")
    op.drop_table("letter")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_newsletter_channel_id"), table_name="newsletter")
    op.drop_table("newsletter")
    # ### end Alembic commands ###
